/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inspired.tx;

import inspired.tx.domain.Account;
import inspired.tx.domain.Currencies;
import inspired.tx.domain.Types;
import inspired.tx.domain.Types.*;
import org.junit.jupiter.api.Test;

import java.math.BigDecimal;
import java.time.LocalDate;

import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {

    private final IBAN iban = new IBAN("DE232323223");
    private final BIC bic = new BIC("SOMEBANK");
    private final AccountHolder holder = new AccountHolder("123", "John Doe");

    @Test void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }

    @Test void testTxLog() {
        InMemoryTransactionLog log = new InMemoryTransactionLog();
        Account account = new Account(iban, bic, holder, log);
        Balance balance = account.getBalance();
        assertEquals(new Balance(new MonetaryAmount(BigDecimal.ZERO, Currencies.EUR), LocalDate.now()), balance);
    }
}
